// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrnekProje.Models;

namespace OrnekProje.Migrations
{
    [DbContext(typeof(ProjeContext))]
    [Migration("20191119003438_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proje.Models.AlinanUrun", b =>
                {
                    b.Property<int>("alinanUrunId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("adet");

                    b.Property<decimal>("birimFiyat");

                    b.Property<int?>("faturaId");

                    b.Property<int?>("musteriId");

                    b.Property<decimal>("toplam");

                    b.Property<string>("urunAdi")
                        .IsRequired();

                    b.HasKey("alinanUrunId");

                    b.HasIndex("faturaId");

                    b.HasIndex("musteriId");

                    b.ToTable("alinanUruns");
                });

            modelBuilder.Entity("Proje.Models.Fatura", b =>
                {
                    b.Property<int>("faturaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("faturaNo");

                    b.Property<DateTime>("faturaTarihi");

                    b.Property<decimal>("genelToplam");

                    b.HasKey("faturaId");

                    b.ToTable("faturas");
                });

            modelBuilder.Entity("Proje.Models.Musteri", b =>
                {
                    b.Property<int>("musteriId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ad");

                    b.Property<string>("adres");

                    b.Property<string>("eposta");

                    b.Property<string>("soyad");

                    b.Property<long>("telefon");

                    b.HasKey("musteriId");

                    b.ToTable("musteris");
                });

            modelBuilder.Entity("Proje.Models.AlinanUrun", b =>
                {
                    b.HasOne("Proje.Models.Fatura", "fatura")
                        .WithMany()
                        .HasForeignKey("faturaId");

                    b.HasOne("Proje.Models.Musteri", "musteri")
                        .WithMany()
                        .HasForeignKey("musteriId");
                });
#pragma warning restore 612, 618
        }
    }
}
